"""News-event fade — sanity backtest on 8 months of M5 data.

Strategy:
  - At T-5min before a high-impact event, capture the M5 close as reference.
  - Place LIMIT orders at +25p (SELL, fade up-spike) and -25p (BUY, fade down).
  - LIMITs valid for 30 min after the nominal event time.
  - On fill: TP at pre-event reference, SL at +1.5x trigger distance past entry,
    time-stop at 60 min post-fill.

Events covered (hardcoded schedules for 2025-08 to 2026-04 window):
  - NFP (1st Friday, 08:30 ET) on EURUSD
  - FOMC rate decision (14:00 ET on FOMC Wednesdays) on EURUSD
  - ECB rate decision (13:15 CET, 12:15 UTC summer / 13:15 UTC winter) on EURUSD

Friction:
  - Spread: rollover-regime estimate (event time ~ extra wide). 5p on EURUSD majors.
  - LIMIT fills are at the LIMIT price (no entry slippage by design).
  - TP/SL: minor slippage (0.5p mean) at exit.

Pair: EURUSD only (most liquid USD-event pair).
"""
from __future__ import annotations
import random
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

UTC = ZoneInfo("UTC")
NY = ZoneInfo("America/New_York")
FRANKFURT = ZoneInfo("Europe/Berlin")
PIP = 0.0001  # EURUSD

STARTING_EQUITY = 700.0
RISK_PCT = 1.0
TRIGGER_PIPS = float(__import__("os").environ.get("TRIGGER_PIPS", "10"))  # LIMIT placed N pips from reference
SL_MULTIPLIER = 1.5  # SL at 1.5x trigger past entry
TIME_STOP_MIN = 60
LIMIT_WINDOW_MIN = 30  # LIMIT live for this many minutes post-event
PRE_EVENT_REF_MIN = 5  # reference price = M5 close 5 min before event
EVENT_SPREAD_PIPS = 5.0  # widened spread at event time
EXIT_SLIPPAGE_MEAN = 0.5
EXIT_SLIPPAGE_STD = 0.3
EXIT_SLIPPAGE_CLIP = (0.0, 2.0)
SEEDS = (1001, 1002, 1003, 1004, 1005)


def ny_to_utc(year, month, day, h, m) -> datetime:
    return datetime(year, month, day, h, m, tzinfo=NY).astimezone(UTC)


def cet_to_utc(year, month, day, h, m) -> datetime:
    return datetime(year, month, day, h, m, tzinfo=FRANKFURT).astimezone(UTC)


# Event schedule — generated by hand from publicly known calendars.
# Times are LOCAL to the source (NY for NFP/FOMC, Frankfurt for ECB).
EVENTS: list[tuple[str, datetime]] = []

# NFP (1st Friday of each month at 08:30 ET) — within our M5 data window
for y, m, d in [
    (2025, 9, 5), (2025, 10, 3), (2025, 11, 7), (2025, 12, 5),
    (2026, 1, 2), (2026, 2, 6), (2026, 3, 6), (2026, 4, 3),
]:
    EVENTS.append(("NFP", ny_to_utc(y, m, d, 8, 30)))

# FOMC (14:00 ET on scheduled Wednesdays)
for y, m, d in [
    (2025, 9, 17), (2025, 10, 29), (2025, 12, 10),
    (2026, 1, 28), (2026, 3, 18),
]:
    EVENTS.append(("FOMC", ny_to_utc(y, m, d, 14, 0)))

# ECB rate decision (13:15 Frankfurt)
for y, m, d in [
    (2025, 9, 11), (2025, 10, 30), (2025, 12, 18),
    (2026, 1, 22), (2026, 3, 5), (2026, 4, 16),
]:
    EVENTS.append(("ECB", cet_to_utc(y, m, d, 13, 15)))


@dataclass
class Trade:
    event_label: str
    event_time: datetime
    direction: str       # LONG (fade down-spike) or SHORT (fade up-spike)
    ref_price: float
    entry_price: float
    sl: float
    tp: float
    entry_time: datetime
    exit_time: datetime | None = None
    exit_price: float | None = None
    exit_reason: str = ""
    pnl_pips: float = 0.0
    pnl_usd: float = 0.0


def apply_exit_slippage_pips(direction_loss_side: bool, rng=None) -> float:
    """Return adverse-slippage pips at exit, gaussian-clipped."""
    r = rng or random
    s = max(EXIT_SLIPPAGE_CLIP[0],
            min(EXIT_SLIPPAGE_CLIP[1],
                r.gauss(EXIT_SLIPPAGE_MEAN, EXIT_SLIPPAGE_STD)))
    return s


def simulate(df: pd.DataFrame) -> list[Trade]:
    """For each event, place LIMITs and simulate fill + exit on M5 bars."""
    trades: list[Trade] = []
    df = df.set_index("time")

    for label, event_time in EVENTS:
        ref_time = event_time - timedelta(minutes=PRE_EVENT_REF_MIN)
        end_window = event_time + timedelta(minutes=LIMIT_WINDOW_MIN)

        # Find the M5 bar at ref_time
        ref_idx = df.index.searchsorted(ref_time)
        if ref_idx >= len(df):
            continue
        ref_bar = df.iloc[ref_idx]
        ref_price = ref_bar["close"]

        long_limit = ref_price - TRIGGER_PIPS * PIP   # BUY at -25p
        short_limit = ref_price + TRIGGER_PIPS * PIP  # SELL at +25p

        # Walk M5 bars in the LIMIT window (event_time to event_time + 30min)
        active_start = event_time
        active_idx = df.index.searchsorted(active_start)
        active_end = end_window

        filled_dir = None
        fill_time = None
        for i in range(active_idx, len(df)):
            t = df.index[i]
            if t >= active_end:
                break
            bar = df.iloc[i]
            # Check both sides — whichever touches first wins.
            # Tie-break: prefer SHORT if both same bar (arbitrary; rare).
            short_hit = bar["high"] >= short_limit
            long_hit = bar["low"] <= long_limit
            if short_hit:
                filled_dir = "SHORT"
                fill_time = t
                break
            if long_hit:
                filled_dir = "LONG"
                fill_time = t
                break

        if filled_dir is None:
            continue

        entry_price = (
            short_limit if filled_dir == "SHORT" else long_limit
        )
        tp = ref_price  # back to pre-event level
        if filled_dir == "LONG":
            sl = entry_price - (SL_MULTIPLIER * TRIGGER_PIPS) * PIP
        else:
            sl = entry_price + (SL_MULTIPLIER * TRIGGER_PIPS) * PIP

        # Walk forward to find exit
        fill_idx = df.index.searchsorted(fill_time)
        exit_deadline = fill_time + timedelta(minutes=TIME_STOP_MIN)
        exit_time = None
        exit_price = None
        exit_reason = ""
        for i in range(fill_idx + 1, len(df)):
            t = df.index[i]
            if t > exit_deadline:
                bar = df.iloc[i - 1]
                exit_time = bar.name
                exit_price = bar["close"]
                exit_reason = "TIME_STOP"
                break
            bar = df.iloc[i]
            if filled_dir == "LONG":
                # TP hit if bar high >= tp; SL hit if bar low <= sl
                if bar["high"] >= tp and bar["low"] <= sl:
                    # Both hit in same bar — assume SL first (worse case)
                    exit_time, exit_price, exit_reason = (
                        t, sl, "SL"
                    )
                    break
                if bar["high"] >= tp:
                    exit_time, exit_price, exit_reason = t, tp, "TP"
                    break
                if bar["low"] <= sl:
                    exit_time, exit_price, exit_reason = t, sl, "SL"
                    break
            else:  # SHORT
                if bar["low"] <= tp and bar["high"] >= sl:
                    exit_time, exit_price, exit_reason = t, sl, "SL"
                    break
                if bar["low"] <= tp:
                    exit_time, exit_price, exit_reason = t, tp, "TP"
                    break
                if bar["high"] >= sl:
                    exit_time, exit_price, exit_reason = t, sl, "SL"
                    break

        if exit_time is None:
            # Ran past end of data
            continue

        # Apply exit slippage on the unfavorable side
        slip = apply_exit_slippage_pips(True) * PIP
        if filled_dir == "LONG":
            exit_fill = exit_price - slip
            pnl_pips = (exit_fill - entry_price) / PIP
        else:
            exit_fill = exit_price + slip
            pnl_pips = (entry_price - exit_fill) / PIP

        # Lot size from risk: stop_pips = SL_MULTIPLIER * TRIGGER_PIPS
        stop_pips = SL_MULTIPLIER * TRIGGER_PIPS
        # Assume $10/pip/standard lot; lots = (equity * risk_pct/100) / (stop_pips * 10)
        # Approximating starting equity for sizing (could compound across trades).
        # For this sanity backtest, fixed sizing keeps the math simple.
        lots = max(round((STARTING_EQUITY * RISK_PCT / 100.0)
                          / (stop_pips * 10.0), 2), 0.01)
        pnl_usd = pnl_pips * lots * 10.0  # $10/pip/lot approximation

        trades.append(Trade(
            event_label=label,
            event_time=event_time,
            direction=filled_dir,
            ref_price=ref_price,
            entry_price=entry_price,
            sl=sl,
            tp=tp,
            entry_time=fill_time,
            exit_time=exit_time,
            exit_price=exit_fill,
            exit_reason=exit_reason,
            pnl_pips=pnl_pips,
            pnl_usd=pnl_usd,
        ))

    return trades


def run_seed(seed: int, df: pd.DataFrame) -> list[Trade]:
    random.seed(seed)
    return simulate(df)


def summarize(trades: list[Trade]) -> dict:
    if not trades:
        return {"n": 0}
    wins = [t for t in trades if t.pnl_pips > 0]
    losses = [t for t in trades if t.pnl_pips <= 0]
    gw = sum(t.pnl_pips for t in wins)
    gl = abs(sum(t.pnl_pips for t in losses))
    return {
        "n": len(trades),
        "wins": len(wins),
        "wr": len(wins) / len(trades) * 100,
        "pf": (gw / gl) if gl > 0 else float("inf"),
        "pips": sum(t.pnl_pips for t in trades),
        "usd": sum(t.pnl_usd for t in trades),
    }


def main():
    df = pd.read_csv(REPO_ROOT / "backtests" / "data" / "EURUSD_M5.csv")
    df["time"] = pd.to_datetime(df["time"], unit="s", utc=True)
    print(
        f"Loaded {len(df)} EURUSD M5 bars "
        f"({df['time'].iloc[0]} → {df['time'].iloc[-1]})"
    )
    print(f"Events in scope: {len(EVENTS)} (NFP/FOMC/ECB)")
    in_window = [
        e for e in EVENTS
        if df["time"].iloc[0] <= e[1] <= df["time"].iloc[-1]
    ]
    print(f"  In M5 window: {len(in_window)}")

    runs = []
    for seed in SEEDS:
        trades = run_seed(seed, df)
        s = summarize(trades)
        runs.append((seed, trades, s))
        if s["n"] > 0:
            print(
                f"seed={seed}: N={s['n']:>3} WR={s['wr']:5.1f}% "
                f"PF={s['pf']:5.2f} pips={s['pips']:+8.1f} "
                f"USD={s['usd']:+7.2f}"
            )
        else:
            print(f"seed={seed}: no trades")

    pfs = [r[2]["pf"] for r in runs if r[2]["n"] > 0]
    if pfs:
        mean_pf = sum(pfs) / len(pfs)
        mean_pips = sum(r[2]["pips"] for r in runs) / len(pfs)
        mean_usd = sum(r[2]["usd"] for r in runs) / len(pfs)
        print(f"\nAcross {len(pfs)} seeds: mean PF {mean_pf:.2f}, mean pips {mean_pips:+.1f}, mean USD ${mean_usd:+.2f}")

    # Use middle seed for the chart + breakdown
    mid_seed, mid_trades, mid_s = runs[len(runs) // 2]
    if not mid_trades:
        print("No trades to chart.")
        return

    # Per-event breakdown
    print(f"\nPer-event breakdown (seed={mid_seed}):")
    print(f"  {'event':<6} {'N':>3} {'WR':>6} {'PF':>6} {'pips':>9}")
    for label in ["NFP", "FOMC", "ECB"]:
        tp = [t for t in mid_trades if t.event_label == label]
        if not tp:
            print(f"  {label:<6} {'0':>3}")
            continue
        wins = [t for t in tp if t.pnl_pips > 0]
        gw = sum(t.pnl_pips for t in wins)
        gl = abs(sum(t.pnl_pips for t in tp if t.pnl_pips <= 0))
        pf = gw / gl if gl else float("inf")
        print(
            f"  {label:<6} {len(tp):>3} {len(wins)/len(tp)*100:>5.1f}% "
            f"{pf:>6.2f} {sum(t.pnl_pips for t in tp):>+9.1f}"
        )

    # Per-reason breakdown
    print(f"\nExit reason breakdown:")
    for reason in ["TP", "SL", "TIME_STOP"]:
        tp = [t for t in mid_trades if t.exit_reason == reason]
        print(f"  {reason:<10} N={len(tp)} avg_pips={sum(t.pnl_pips for t in tp) / max(len(tp), 1):+.1f}")

    # Equity curve
    mid_trades.sort(key=lambda t: t.exit_time or datetime.min.replace(tzinfo=UTC))
    times = [t.entry_time for t in mid_trades[:1]] + [t.exit_time for t in mid_trades]
    eq = [STARTING_EQUITY]
    for t in mid_trades:
        eq.append(eq[-1] + t.pnl_usd)
    peak = np.maximum.accumulate(np.array(eq))
    dd = (np.array(eq) - peak) / peak * 100
    max_dd = abs(dd.min())
    ret_pct = (eq[-1] - STARTING_EQUITY) / STARTING_EQUITY * 100

    fig, axes = plt.subplots(
        2, 1, figsize=(14, 8),
        gridspec_kw={"height_ratios": [3, 1], "hspace": 0.3},
    )
    ax1 = axes[0]
    ax1.plot(times, eq, color="steelblue", linewidth=1.5, marker="o", markersize=4)
    ax1.fill_between(times, STARTING_EQUITY, eq, alpha=0.15, color="steelblue")
    ax1.axhline(y=STARTING_EQUITY, color="gray", linestyle="--", alpha=0.4)
    ax1.set_title(
        f"News-Event Fade (EURUSD M5) — ${STARTING_EQUITY:.0f} -> ${eq[-1]:,.2f} "
        f"({ret_pct:+.1f}%)\n"
        f"N={len(mid_trades)} trades, PF={mid_s['pf']:.2f}, "
        f"WR={mid_s['wr']:.1f}%, MaxDD={max_dd:.1f}%, seed={mid_seed}",
        fontsize=12, fontweight="bold", linespacing=1.4,
    )
    ax1.set_ylabel("Equity ($)")
    ax1.grid(True, alpha=0.3)

    ax2 = axes[1]
    ax2.fill_between(times, dd, 0, color="red", alpha=0.3)
    ax2.plot(times, dd, color="red", linewidth=0.7)
    ax2.set_ylabel("Drawdown (%)")
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim(top=1)

    out_png = REPO_ROOT / "backtests" / "charts" / "news_fade_validation.png"
    plt.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"\nSaved equity curve: {out_png}")


if __name__ == "__main__":
    main()
